import { useState } from 'react';
import { useServerFn } from '@tanstack/react-start';
import { Network, Loader2, Plus, Minus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { checkInteractions } from '@/lib/interactions.functions';
import { storeInteraction, useInteractions } from '@/lib/interaction-store';
import { patients } from '@/lib/recall-matching';
import { regimenFingerprint } from '@/lib/interaction-types';
export function InteractionGraph({patientId,name}:{patientId:string;name:string}) {
 const all=useInteractions(); const patient=patients.find(p=>p.id===patientId); const stored=all[patientId]; const result=patient && stored?.fingerprint===regimenFingerprint(patient)?stored:undefined;
 const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [selected,setSelected]=useState('');const [zoom,setZoom]=useState(1);
 const check=useServerFn(checkInteractions);
 async function generate(){setOpen(true);setBusy(true);setError('');try{const response=await check({data:{patientId,explain:true}});if(response.ok)storeInteraction(response.result);else setError(response.message);}catch(e){setError(e instanceof Error?e.message:'Interaction graph failed.');}finally{setBusy(false);}}
 const points=result?.nodes.map((node,i,arr)=>({...node,x:300+205*Math.cos(2*Math.PI*i/Math.max(arr.length,1)),y:190+125*Math.sin(2*Math.PI*i/Math.max(arr.length,1))}))??[];
 const edge=result?.edges.find(e=>e.id===selected);
 return <><Button variant="outline" size="sm" onClick={()=>{if(result?.summary)setOpen(true);else void generate();}}><Network className="h-4 w-4" />{result?.summary?'View interaction graph':'Create interaction graph'}</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>Medication interactions · {name}</DialogTitle><DialogDescription>Potential label conflicts · pharmacist review required</DialogDescription></DialogHeader>
 {busy&&<p role="status" className="flex items-center gap-2 text-sm"><Loader2 className="h-4 w-4 animate-spin"/>Checking FDA evidence and preparing Gemini explanations…</p>}{error&&<div role="alert" className="text-sm text-destructive">{error}<Button variant="outline" onClick={()=>void generate()} disabled={busy}>Try again</Button></div>}
 {result&&<><div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span>{result.pairsChecked} medication pairs · {result.edges.length} evidence links · {new Date(result.checkedAt).toLocaleString()}</span><div className="flex gap-1"><Button variant="ghost" size="icon" aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.7,z-.2))}><Minus/></Button><Button variant="ghost" size="icon" aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(2,z+.2))}><Plus/></Button></div></div>
 <div className="overflow-auto rounded-md border bg-muted/30"><svg viewBox="0 0 600 380" className="min-w-[520px] w-full" role="img" aria-label="Medication and allergy interaction graph"><g transform={`translate(300 190) scale(${zoom}) translate(-300 -190)`}>{result.edges.map(e=>{const a=points.find(p=>p.id===e.source),b=points.find(p=>p.id===e.target);if(!a||!b)return null;return <g key={e.id} role="button" tabIndex={0} aria-label={`Review ${a.label} and ${b.label}`} onClick={()=>setSelected(e.id)} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();setSelected(e.id);}}} className="cursor-pointer text-warning"><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="currentColor" strokeWidth={selected===e.id?6:3}/><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="transparent" strokeWidth={20}/></g>;})}{points.map(p=><g key={p.id}><circle cx={p.x} cy={p.y} r={24} className={p.kind==='allergy'?'fill-warning stroke-warning':'fill-card stroke-primary'} strokeWidth={3}/><text x={p.x} y={p.y+5} textAnchor="middle" className="fill-foreground text-xs">{p.kind==='allergy'?'A':'Rx'}</text><text x={p.x} y={p.y+43} textAnchor="middle" className="fill-foreground text-[10px]">{p.label.slice(0,32)}</text></g>)}</g></svg></div>
 <p className="text-sm">{result.summary??'FDA label screening complete. Gemini explanation has not been generated.'}</p>{!result.nodes.length&&<p className="text-sm">No medications fall within the recorded active supply window. Confirm the current regimen.</p>}
 <div className="flex flex-wrap gap-2">{result.edges.map((e,i)=><Button key={e.id} size="sm" variant={selected===e.id?'secondary':'outline'} onClick={()=>setSelected(e.id)}>{e.kind==='allergy'?'Allergy':'Interaction'} evidence {i+1}</Button>)}</div>
 {edge&&<section className="space-y-3 border-l-4 border-warning pl-4"><h3 className="font-semibold">{points.find(p=>p.id===edge.source)?.label} ↔ {points.find(p=>p.id===edge.target)?.label}</h3><p className="text-sm">{edge.explanation??'Potential label mention. Confirm clinical relevance with a pharmacist.'}</p><blockquote className="max-h-44 overflow-y-auto text-sm text-muted-foreground">{edge.quote}</blockquote><a href={edge.url} target="_blank" rel="noreferrer" className="text-sm text-primary underline">Exact FDA label record</a></section>}
 {!result.edges.length&&<p className="text-sm font-medium">No explicit label mentions identified — this is not a safety clearance.</p>}<ul className="space-y-1 text-xs text-muted-foreground">{result.gaps.map((gap,i)=><li key={i}>• {gap}</li>)}</ul></>}
 </DialogContent></Dialog></>;
}
